### ISSUE TITLE
please specify which version of luarocks to use

### ISSUE THREAD

**Issue by Grimmoire** [steinuil/mpv-livetweet#1]
i installed 5.1, 5.2, and the newest one and installed all the packages like three times and then when i ran the script i found that i also needed luasocket as a dependency. also fucking luarocks tells you it's missing dependencies then fucking tries and fails to build the package. 30 packages installed later and i'm surprised i actually got this working

**Comment by steinuil** [comment]
Everybody who tried to install this script had problems with luarocks, the problem is that I have absolutely no idea how I made it work so all I can tell you if you want to try running this thing is "good luck m8"

I'm using LuaRocks 2.2.0 on Lua 5.1 right now and (after hours of cursing and changing config files) it works, the only thing I had to do when I set it up right was running `sudo luarocks install luatwit luasocket oauth`. It used to work on my other computer with Lua 5.2 too though (I think I remember I had problems there too) so I really have no fucking idea, LuaRocks can seriously go fuck itself.

**Comment by Grimmoire** [comment]
well, in my experience, at least, luarocks is still better than pip. i just removed everything but the 5.2 packages and it still works idk if that's helpful information or not. anyway, thanks for the script i really like it

**Comment by steinuil** [comment]
It might be. I have exams right now so I'm kinda busy but when I'm done I might experiment a bit with stuff and see if you need to use some specific version of Lua or whatever and try to see what can be done with Windows compatibility.
You're welcome, I'm glad somebody other than me finds this useful.
